# Generated by Django 4.1.4 on 2024-01-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО обучающегося')),
                ('personal_number', models.CharField(max_length=20, verbose_name='Личный номер')),
                ('contract_number', models.CharField(max_length=255, verbose_name='Номер договора')),
                ('accounts_receivable', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма задолженности')),
                ('status', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('file_created_time', models.DateTimeField(verbose_name='Дата создания файла')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Задолженность студентов',
                'verbose_name_plural': 'Задолженность студентов',
            },
        ),
    ]
